apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/XMOTECH/gitops-labs.git
    targetRevision: main
    path: apps/portfolio/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
